// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SepTier3.Data;

namespace SepTier3.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20191205120316_V5")]
    partial class V5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SepTier3.Data.Entities.Bin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("BinType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Bins");
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressBlock")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("AddressNr")
                        .HasColumnType("int");

                    b.Property<int>("AppartmentNr")
                        .HasColumnType("int");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("HomeNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNONr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IdReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressBlock")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("AddressNr")
                        .HasColumnType("int");

                    b.Property<int>("AppartmentNr")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IDNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNONr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IdReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidApr")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidAug")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidDec")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidFeb")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidJan")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidJul")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidJun")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidMar")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidMay")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidNov")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidOct")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaidSep")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayApr")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayAug")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayDec")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayFeb")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayJan")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayJul")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayJun")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayMar")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayMay")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayNov")
                        .HasColumnType("int");

                    b.Property<int>("MonthPayOct")
                        .HasColumnType("int");

                    b.Property<int>("MonthPaySep")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenPaidApr")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidAug")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidDec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidFeb")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidJan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidJul")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidJun")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidMar")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidMay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidNov")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidOct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WhenPaidSep")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Trash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Trashes");
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Bin", b =>
                {
                    b.HasOne("SepTier3.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SepTier3.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Contract", b =>
                {
                    b.HasOne("SepTier3.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SepTier3.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Invoice", b =>
                {
                    b.HasOne("SepTier3.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SepTier3.Data.Entities.Trash", b =>
                {
                    b.HasOne("SepTier3.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SepTier3.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
